# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pinvgauss_export <- function(x, a, b) {
    .Call(`_cobin_pinvgauss_export`, x, a, b)
}

pgig_onehalf_export <- function(x, a, b) {
    .Call(`_cobin_pgig_onehalf_export`, x, a, b)
}

pgig_negonehalf_export <- function(x, a, b) {
    .Call(`_cobin_pgig_negonehalf_export`, x, a, b)
}

#' @export
rkgcpp <- function(n, b, z) {
    .Call(`_cobin_rkgcpp`, n, b, z)
}

rinvgauss_mulambda_export <- function(n, mu, lambda) {
    .Call(`_cobin_rinvgauss_mulambda_export`, n, mu, lambda)
}

rgig_negonehalf_export <- function(n, a, b) {
    .Call(`_cobin_rgig_negonehalf_export`, n, a, b)
}

